// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// RIDGEc
arma::mat RIDGEc(const arma::mat& S, double lam);
RcppExport SEXP _shrink_RIDGEc(SEXP SSEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(RIDGEc(S, lam));
    return rcpp_result_gen;
END_RCPP
}
// ADMMc
List ADMMc(const arma::mat& S, const arma::mat& A, const arma::mat& B, const arma::mat& C, const arma::mat& initOmega, const arma::mat& initZ2, const arma::mat& initY, const double lam, double rho, const double mu, const double tau_inc, const double tau_dec, std::string crit, const double tol_abs, const double tol_rel, const int maxit);
RcppExport SEXP _shrink_ADMMc(SEXP SSEXP, SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP initOmegaSEXP, SEXP initZ2SEXP, SEXP initYSEXP, SEXP lamSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP tau_incSEXP, SEXP tau_decSEXP, SEXP critSEXP, SEXP tol_absSEXP, SEXP tol_relSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initOmega(initOmegaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initZ2(initZ2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initY(initYSEXP);
    Rcpp::traits::input_parameter< const double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_inc(tau_incSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_dec(tau_decSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit(critSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(ADMMc(S, A, B, C, initOmega, initZ2, initY, lam, rho, mu, tau_inc, tau_dec, crit, tol_abs, tol_rel, maxit));
    return rcpp_result_gen;
END_RCPP
}
// CV_ADMMc
List CV_ADMMc(const arma::mat& X, const arma::mat& S, const arma::mat& Y, const arma::mat& A, const arma::mat& B, const arma::mat& C, const arma::colvec& lam, bool path, double rho, const double mu, const double tau_inc, const double tau_dec, std::string crit, const double tol_abs, const double tol_rel, int maxit, int adjmaxit, int K, std::string crit_cv, std::string start, std::string trace);
RcppExport SEXP _shrink_CV_ADMMc(SEXP XSEXP, SEXP SSEXP, SEXP YSEXP, SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP lamSEXP, SEXP pathSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP tau_incSEXP, SEXP tau_decSEXP, SEXP critSEXP, SEXP tol_absSEXP, SEXP tol_relSEXP, SEXP maxitSEXP, SEXP adjmaxitSEXP, SEXP KSEXP, SEXP crit_cvSEXP, SEXP startSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< bool >::type path(pathSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_inc(tau_incSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_dec(tau_decSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit(critSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type adjmaxit(adjmaxitSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_cv(crit_cvSEXP);
    Rcpp::traits::input_parameter< std::string >::type start(startSEXP);
    Rcpp::traits::input_parameter< std::string >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(CV_ADMMc(X, S, Y, A, B, C, lam, path, rho, mu, tau_inc, tau_dec, crit, tol_abs, tol_rel, maxit, adjmaxit, K, crit_cv, start, trace));
    return rcpp_result_gen;
END_RCPP
}
// CVP_ADMMc
arma::mat CVP_ADMMc(const arma::mat& X_train, const arma::mat& X_valid, const arma::mat& Y_train, const arma::mat& Y_valid, const arma::mat& A, const arma::mat& B, const arma::mat& C, const arma::colvec& lam, double rho, const double mu, const double tau_inc, const double tau_dec, std::string crit, const double tol_abs, const double tol_rel, int maxit, int adjmaxit, std::string crit_cv, std::string start, std::string trace);
RcppExport SEXP _shrink_CVP_ADMMc(SEXP X_trainSEXP, SEXP X_validSEXP, SEXP Y_trainSEXP, SEXP Y_validSEXP, SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP lamSEXP, SEXP rhoSEXP, SEXP muSEXP, SEXP tau_incSEXP, SEXP tau_decSEXP, SEXP critSEXP, SEXP tol_absSEXP, SEXP tol_relSEXP, SEXP maxitSEXP, SEXP adjmaxitSEXP, SEXP crit_cvSEXP, SEXP startSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_train(X_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_valid(X_validSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_train(Y_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_valid(Y_validSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_inc(tau_incSEXP);
    Rcpp::traits::input_parameter< const double >::type tau_dec(tau_decSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit(critSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_rel(tol_relSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< int >::type adjmaxit(adjmaxitSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_cv(crit_cvSEXP);
    Rcpp::traits::input_parameter< std::string >::type start(startSEXP);
    Rcpp::traits::input_parameter< std::string >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(CVP_ADMMc(X_train, X_valid, Y_train, Y_valid, A, B, C, lam, rho, mu, tau_inc, tau_dec, crit, tol_abs, tol_rel, maxit, adjmaxit, crit_cv, start, trace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shrink_RIDGEc", (DL_FUNC) &_shrink_RIDGEc, 2},
    {"_shrink_ADMMc", (DL_FUNC) &_shrink_ADMMc, 16},
    {"_shrink_CV_ADMMc", (DL_FUNC) &_shrink_CV_ADMMc, 21},
    {"_shrink_CVP_ADMMc", (DL_FUNC) &_shrink_CVP_ADMMc, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_shrink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
